### ISSUE TITLE
How to make this work

### ISSUE THREAD

**Issue by Vertical2222** [TypicalModMaker/qChecker#2]
I have fs.txt file which contains server ips and port
format:
103.42.42.42:25566
103.42.56.24:25577
just example ips
then i do java -jar qChecker.jar fs.txt
it returns: 
found 0 servers
although i used mcsrvstat.us to make sure that atleast 1 server is ip forward-able but qchecker returns 0 server was found

**Comment by TypicalModMaker** [comment]
you provide servers in quboscanner output, not ip:port
